homeassistant:
  url: https://your.hass.install.here/
  token: your_long_lived_token_here
  monitoring:
    enabled: false
    port: 8080
terminal:
  port: /dev/ttyUSB0
  baud: 9600
general:
  name: Home Assistant Dashboard
  show_help: False
layout:
  - name: Tab 1
    entities:
     - entity1
     - entity2
